version: "3.3"

services:
  mysqlAutoBackup:
    container_name: mysqlAutoBackup
    image: devlifex/mysql-auto-backup
    restart: always
    environment:
      # Every Hour By Default
      # CRONTAB: "0 * * * *"
      CRONTAB: "* * * * *"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/.ssh:/root/.ssh:ro
      - ./backup-file:/root/backup-file
      - ./servers.yml:/root/servers.yml
