version: "3.3"

services:
  mysqlAutoBackup:
    container_name: mysqlAutoBackup
    image: devlifex/mysql-auto-backup
    restart: always
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ./backup-file:/root/backup-file
      - ./servers.yml:/root/servers.yml
